export const getFlagImageSource = countryCode => {
  switch (countryCode.toUpperCase()) {
    case 'AF':
      return require('./flags/af.png');
    case 'AX':
      return require('./flags/ax.png');
    case 'AL':
      return require('./flags/al.png');
    case 'DZ':
      return require('./flags/dz.png');
    case 'AS':
      return require('./flags/as.png');
    case 'AD':
      return require('./flags/ad.png');
    case 'AO':
      return require('./flags/ao.png');
    case 'AI':
      return require('./flags/ai.png');
    case 'AQ':
      return require('./flags/aq.png');
    case 'AG':
      return require('./flags/ag.png');
    case 'AR':
      return require('./flags/ar.png');
    case 'AM':
      return require('./flags/am.png');
    case 'AW':
      return require('./flags/aw.png');
    case 'AU':
      return require('./flags/au.png');
    case 'AT':
      return require('./flags/at.png');
    case 'AZ':
      return require('./flags/az.png');
    case 'BS':
      return require('./flags/bs.png');
    case 'BH':
      return require('./flags/bh.png');
    case 'BD':
      return require('./flags/bd.png');
    case 'BB':
      return require('./flags/bb.png');
    case 'BY':
      return require('./flags/by.png');
    case 'BE':
      return require('./flags/be.png');
    case 'BZ':
      return require('./flags/bz.png');
    case 'BJ':
      return require('./flags/bj.png');
    case 'BM':
      return require('./flags/bm.png');
    case 'BT':
      return require('./flags/bt.png');
    case 'BO':
      return require('./flags/bo.png');
    case 'BQ':
      return require('./flags/bq.png');
    case 'BA':
      return require('./flags/ba.png');
    case 'BW':
      return require('./flags/bw.png');
    case 'BV':
      return require('./flags/bv.png');
    case 'BR':
      return require('./flags/br.png');
    case 'IO':
      return require('./flags/io.png');
    case 'BN':
      return require('./flags/bn.png');
    case 'BG':
      return require('./flags/bg.png');
    case 'BF':
      return require('./flags/bf.png');
    case 'BI':
      return require('./flags/bi.png');
    case 'KH':
      return require('./flags/kh.png');
    case 'CM':
      return require('./flags/cm.png');
    case 'CA':
      return require('./flags/ca.png');
    case 'CV':
      return require('./flags/cv.png');
    case 'KY':
      return require('./flags/ky.png');
    case 'CF':
      return require('./flags/cf.png');
    case 'TD':
      return require('./flags/td.png');
    case 'CL':
      return require('./flags/cl.png');
    case 'CN':
      return require('./flags/cn.png');
    case 'CX':
      return require('./flags/cx.png');
    case 'CC':
      return require('./flags/cc.png');
    case 'CO':
      return require('./flags/co.png');
    case 'KM':
      return require('./flags/km.png');
    case 'CG':
      return require('./flags/cg.png');
    case 'CD':
      return require('./flags/cd.png');
    case 'CK':
      return require('./flags/ck.png');
    case 'CR':
      return require('./flags/cr.png');
    case 'CI':
      return require('./flags/ci.png');
    case 'HR':
      return require('./flags/hr.png');
    case 'CU':
      return require('./flags/cu.png');
    case 'CW':
      return require('./flags/cw.png');
    case 'CY':
      return require('./flags/cy.png');
    case 'CZ':
      return require('./flags/cz.png');
    case 'DK':
      return require('./flags/dk.png');
    case 'DJ':
      return require('./flags/dj.png');
    case 'DM':
      return require('./flags/dm.png');
    case 'DO':
      return require('./flags/do.png');
    case 'EC':
      return require('./flags/ec.png');
    case 'EG':
      return require('./flags/eg.png');
    case 'SV':
      return require('./flags/sv.png');
    case 'GQ':
      return require('./flags/gq.png');
    case 'ER':
      return require('./flags/er.png');
    case 'EE':
      return require('./flags/ee.png');
    case 'SZ':
      return require('./flags/sz.png');
    case 'ET':
      return require('./flags/et.png');
    case 'FK':
      return require('./flags/fk.png');
    case 'FO':
      return require('./flags/fo.png');
    case 'FJ':
      return require('./flags/fj.png');
    case 'FI':
      return require('./flags/fi.png');
    case 'FR':
      return require('./flags/fr.png');
    case 'GF':
      return require('./flags/gf.png');
    case 'PF':
      return require('./flags/pf.png');
    case 'TF':
      return require('./flags/tf.png');
    case 'GA':
      return require('./flags/ga.png');
    case 'GM':
      return require('./flags/gm.png');
    case 'GE':
      return require('./flags/ge.png');
    case 'DE':
      return require('./flags/de.png');
    case 'GH':
      return require('./flags/gh.png');
    case 'GI':
      return require('./flags/gi.png');
    case 'GR':
      return require('./flags/gr.png');
    case 'GL':
      return require('./flags/gl.png');
    case 'GD':
      return require('./flags/gd.png');
    case 'GP':
      return require('./flags/gp.png');
    case 'GU':
      return require('./flags/gu.png');
    case 'GT':
      return require('./flags/gt.png');
    case 'GG':
      return require('./flags/gg.png');
    case 'GN':
      return require('./flags/gn.png');
    case 'GW':
      return require('./flags/gw.png');
    case 'GY':
      return require('./flags/gy.png');
    case 'HT':
      return require('./flags/ht.png');
    case 'HM':
      return require('./flags/hm.png');
    case 'VA':
      return require('./flags/va.png');
    case 'HN':
      return require('./flags/hn.png');
    case 'HK':
      return require('./flags/hk.png');
    case 'HU':
      return require('./flags/hu.png');
    case 'IS':
      return require('./flags/is.png');
    case 'IN':
      return require('./flags/in.png');
    case 'ID':
      return require('./flags/id.png');
    case 'IR':
      return require('./flags/ir.png');
    case 'IQ':
      return require('./flags/iq.png');
    case 'IE':
      return require('./flags/ie.png');
    case 'IM':
      return require('./flags/im.png');
    case 'IL':
      return require('./flags/il.png');
    case 'IT':
      return require('./flags/it.png');
    case 'JM':
      return require('./flags/jm.png');
    case 'JP':
      return require('./flags/jp.png');
    case 'JE':
      return require('./flags/je.png');
    case 'JO':
      return require('./flags/jo.png');
    case 'KZ':
      return require('./flags/kz.png');
    case 'KE':
      return require('./flags/ke.png');
    case 'KI':
      return require('./flags/ki.png');
    case 'KP':
      return require('./flags/kp.png');
    case 'KR':
      return require('./flags/kr.png');
    case 'KW':
      return require('./flags/kw.png');
    case 'KG':
      return require('./flags/kg.png');
    case 'LA':
      return require('./flags/la.png');
    case 'LV':
      return require('./flags/lv.png');
    case 'LB':
      return require('./flags/lb.png');
    case 'LS':
      return require('./flags/ls.png');
    case 'LR':
      return require('./flags/lr.png');
    case 'LY':
      return require('./flags/ly.png');
    case 'LI':
      return require('./flags/li.png');
    case 'LT':
      return require('./flags/lt.png');
    case 'LU':
      return require('./flags/lu.png');
    case 'MO':
      return require('./flags/mo.png');
    case 'MK':
      return require('./flags/mk.png');
    case 'MG':
      return require('./flags/mg.png');
    case 'MW':
      return require('./flags/mw.png');
    case 'MY':
      return require('./flags/my.png');
    case 'MV':
      return require('./flags/mv.png');
    case 'ML':
      return require('./flags/ml.png');
    case 'MT':
      return require('./flags/mt.png');
    case 'MH':
      return require('./flags/mh.png');
    case 'MQ':
      return require('./flags/mq.png');
    case 'MR':
      return require('./flags/mr.png');
    case 'MU':
      return require('./flags/mu.png');
    case 'YT':
      return require('./flags/yt.png');
    case 'MX':
      return require('./flags/mx.png');
    case 'FM':
      return require('./flags/fm.png');
    case 'MD':
      return require('./flags/md.png');
    case 'MC':
      return require('./flags/mc.png');
    case 'MN':
      return require('./flags/mn.png');
    case 'ME':
      return require('./flags/me.png');
    case 'MS':
      return require('./flags/ms.png');
    case 'MA':
      return require('./flags/ma.png');
    case 'MZ':
      return require('./flags/mz.png');
    case 'MM':
      return require('./flags/mm.png');
    case 'NA':
      return require('./flags/na.png');
    case 'NR':
      return require('./flags/nr.png');
    case 'NP':
      return require('./flags/np.png');
    case 'NL':
      return require('./flags/nl.png');
    case 'NC':
      return require('./flags/nc.png');
    case 'NZ':
      return require('./flags/nz.png');
    case 'NI':
      return require('./flags/ni.png');
    case 'NE':
      return require('./flags/ne.png');
    case 'NG':
      return require('./flags/ng.png');
    case 'NU':
      return require('./flags/nu.png');
    case 'NF':
      return require('./flags/nf.png');
    case 'MP':
      return require('./flags/mp.png');
    case 'NO':
      return require('./flags/no.png');
    case 'OM':
      return require('./flags/om.png');
    case 'PK':
      return require('./flags/pk.png');
    case 'PW':
      return require('./flags/pw.png');
    case 'PS':
      return require('./flags/ps.png');
    case 'PA':
      return require('./flags/pa.png');
    case 'PG':
      return require('./flags/pg.png');
    case 'PY':
      return require('./flags/py.png');
    case 'PE':
      return require('./flags/pe.png');
    case 'PH':
      return require('./flags/ph.png');
    case 'PN':
      return require('./flags/pn.png');
    case 'PL':
      return require('./flags/pl.png');
    case 'PT':
      return require('./flags/pt.png');
    case 'PR':
      return require('./flags/pr.png');
    case 'QA':
      return require('./flags/qa.png');
    case 'RE':
      return require('./flags/re.png');
    case 'RO':
      return require('./flags/ro.png');
    case 'RU':
      return require('./flags/ru.png');
    case 'RW':
      return require('./flags/rw.png');
    case 'BL':
      return require('./flags/bl.png');
    case 'SH':
      return require('./flags/sh.png');
    case 'KN':
      return require('./flags/kn.png');
    case 'LC':
      return require('./flags/lc.png');
    case 'MF':
      return require('./flags/mf.png');
    case 'PM':
      return require('./flags/pm.png');
    case 'VC':
      return require('./flags/vc.png');
    case 'WS':
      return require('./flags/ws.png');
    case 'SM':
      return require('./flags/sm.png');
    case 'ST':
      return require('./flags/st.png');
    case 'SA':
      return require('./flags/sa.png');
    case 'SN':
      return require('./flags/sn.png');
    case 'RS':
      return require('./flags/rs.png');
    case 'SC':
      return require('./flags/sc.png');
    case 'SL':
      return require('./flags/sl.png');
    case 'SG':
      return require('./flags/sg.png');
    case 'SX':
      return require('./flags/sx.png');
    case 'SK':
      return require('./flags/sk.png');
    case 'SI':
      return require('./flags/si.png');
    case 'SB':
      return require('./flags/sb.png');
    case 'SO':
      return require('./flags/so.png');
    case 'ZA':
      return require('./flags/za.png');
    case 'GS':
      return require('./flags/gs.png');
    case 'SS':
      return require('./flags/ss.png');
    case 'ES':
      return require('./flags/es.png');
    case 'LK':
      return require('./flags/lk.png');
    case 'SD':
      return require('./flags/sd.png');
    case 'SR':
      return require('./flags/sr.png');
    case 'SJ':
      return require('./flags/sj.png');
    case 'SE':
      return require('./flags/se.png');
    case 'CH':
      return require('./flags/ch.png');
    case 'SY':
      return require('./flags/sy.png');
    case 'TW':
      return require('./flags/tw.png');
    case 'TJ':
      return require('./flags/tj.png');
    case 'TZ':
      return require('./flags/tz.png');
    case 'TH':
      return require('./flags/th.png');
    case 'TL':
      return require('./flags/tl.png');
    case 'TG':
      return require('./flags/tg.png');
    case 'TK':
      return require('./flags/tk.png');
    case 'TO':
      return require('./flags/to.png');
    case 'TT':
      return require('./flags/tt.png');
    case 'TN':
      return require('./flags/tn.png');
    case 'TR':
      return require('./flags/tr.png');
    case 'TM':
      return require('./flags/tm.png');
    case 'TC':
      return require('./flags/tc.png');
    case 'TV':
      return require('./flags/tv.png');
    case 'UG':
      return require('./flags/ug.png');
    case 'UA':
      return require('./flags/ua.png');
    case 'AE':
      return require('./flags/ae.png');
    case 'GB':
      return require('./flags/gb.png');
    case 'US':
      return require('./flags/us.png');
    case 'UM':
      return require('./flags/um.png');
    case 'UY':
      return require('./flags/uy.png');
    case 'UZ':
      return require('./flags/uz.png');
    case 'VU':
      return require('./flags/vu.png');
    case 'VE':
      return require('./flags/ve.png');
    case 'VN':
      return require('./flags/vn.png');
    case 'VG':
      return require('./flags/vg.png');
    case 'VI':
      return require('./flags/vi.png');
    case 'WF':
      return require('./flags/wf.png');
    case 'EH':
      return require('./flags/eh.png');
    case 'YE':
      return require('./flags/ye.png');
    case 'ZM':
      return require('./flags/zm.png');
    case 'ZW':
      return require('./flags/zw.png');
    default:
      return require('./flags/white.jpg'); // Fallback image if countryCode doesn't match any case
  }
};
